/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminOptionsRouteImport } from './routes/admin.options'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin.templates.index'
import { Route as AdminOptionsIndexRouteImport } from './routes/admin.options.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminApiKeysIndexRouteImport } from './routes/admin.api-keys.index'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app.templates.index'
import { Route as AppGeneratorIndexRouteImport } from './routes/_app.generator.index'
import { Route as AdminTemplatesCreateRouteImport } from './routes/admin.templates.create'
import { Route as AdminOptionsCreateRouteImport } from './routes/admin.options.create'
import { Route as AdminCategoriesCreateRouteImport } from './routes/admin.categories.create'
import { Route as AdminApiKeysCreateRouteImport } from './routes/admin.api-keys.create'
import { Route as AppTemplatesSlugRouteImport } from './routes/_app.templates.$slug'
import { Route as AppGeneratorResultRouteImport } from './routes/_app.generator.result'
import { Route as AdminTemplatesIdEditRouteImport } from './routes/admin.templates.$id.edit'
import { Route as AdminOptionsIdEditRouteImport } from './routes/admin.options.$id.edit'
import { Route as AdminCategoriesIdEditRouteImport } from './routes/admin.categories.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOptionsRoute = AdminOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const AdminOptionsIndexRoute = AdminOptionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOptionsRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminApiKeysIndexRoute = AdminApiKeysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminApiKeysRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorIndexRoute = AppGeneratorIndexRouteImport.update({
  id: '/generator/',
  path: '/generator/',
  getParentRoute: () => AppRoute,
} as any)
const AdminTemplatesCreateRoute = AdminTemplatesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const AdminOptionsCreateRoute = AdminOptionsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminOptionsRoute,
} as any)
const AdminCategoriesCreateRoute = AdminCategoriesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminApiKeysCreateRoute = AdminApiKeysCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminApiKeysRoute,
} as any)
const AppTemplatesSlugRoute = AppTemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorResultRoute = AppGeneratorResultRouteImport.update({
  id: '/generator/result',
  path: '/generator/result',
  getParentRoute: () => AppRoute,
} as any)
const AdminTemplatesIdEditRoute = AdminTemplatesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const AdminOptionsIdEditRoute = AdminOptionsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminOptionsRoute,
} as any)
const AdminCategoriesIdEditRoute = AdminCategoriesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminCategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/admin/api-keys': typeof AdminApiKeysRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/options': typeof AdminOptionsRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/generator/result': typeof AppGeneratorResultRoute
  '/templates/$slug': typeof AppTemplatesSlugRoute
  '/admin/api-keys/create': typeof AdminApiKeysCreateRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/options/create': typeof AdminOptionsCreateRoute
  '/admin/templates/create': typeof AdminTemplatesCreateRoute
  '/generator/': typeof AppGeneratorIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/admin/api-keys/': typeof AdminApiKeysIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/options/': typeof AdminOptionsIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/options/$id/edit': typeof AdminOptionsIdEditRoute
  '/admin/templates/$id/edit': typeof AdminTemplatesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/generator/result': typeof AppGeneratorResultRoute
  '/templates/$slug': typeof AppTemplatesSlugRoute
  '/admin/api-keys/create': typeof AdminApiKeysCreateRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/options/create': typeof AdminOptionsCreateRoute
  '/admin/templates/create': typeof AdminTemplatesCreateRoute
  '/generator': typeof AppGeneratorIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/admin/api-keys': typeof AdminApiKeysIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/options': typeof AdminOptionsIndexRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/options/$id/edit': typeof AdminOptionsIdEditRoute
  '/admin/templates/$id/edit': typeof AdminTemplatesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/admin/api-keys': typeof AdminApiKeysRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/options': typeof AdminOptionsRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/_app/generator/result': typeof AppGeneratorResultRoute
  '/_app/templates/$slug': typeof AppTemplatesSlugRoute
  '/admin/api-keys/create': typeof AdminApiKeysCreateRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/options/create': typeof AdminOptionsCreateRoute
  '/admin/templates/create': typeof AdminTemplatesCreateRoute
  '/_app/generator/': typeof AppGeneratorIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/admin/api-keys/': typeof AdminApiKeysIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/options/': typeof AdminOptionsIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/options/$id/edit': typeof AdminOptionsIdEditRoute
  '/admin/templates/$id/edit': typeof AdminTemplatesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/settings'
    | '/admin/api-keys'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/options'
    | '/admin/templates'
    | '/admin/users'
    | '/generator/result'
    | '/templates/$slug'
    | '/admin/api-keys/create'
    | '/admin/categories/create'
    | '/admin/options/create'
    | '/admin/templates/create'
    | '/generator/'
    | '/templates/'
    | '/admin/api-keys/'
    | '/admin/categories/'
    | '/admin/options/'
    | '/admin/templates/'
    | '/admin/users/'
    | '/admin/categories/$id/edit'
    | '/admin/options/$id/edit'
    | '/admin/templates/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/settings'
    | '/admin/dashboard'
    | '/generator/result'
    | '/templates/$slug'
    | '/admin/api-keys/create'
    | '/admin/categories/create'
    | '/admin/options/create'
    | '/admin/templates/create'
    | '/generator'
    | '/templates'
    | '/admin/api-keys'
    | '/admin/categories'
    | '/admin/options'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/categories/$id/edit'
    | '/admin/options/$id/edit'
    | '/admin/templates/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/profile'
    | '/_app/settings'
    | '/admin/api-keys'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/options'
    | '/admin/templates'
    | '/admin/users'
    | '/_app/generator/result'
    | '/_app/templates/$slug'
    | '/admin/api-keys/create'
    | '/admin/categories/create'
    | '/admin/options/create'
    | '/admin/templates/create'
    | '/_app/generator/'
    | '/_app/templates/'
    | '/admin/api-keys/'
    | '/admin/categories/'
    | '/admin/options/'
    | '/admin/templates/'
    | '/admin/users/'
    | '/admin/categories/$id/edit'
    | '/admin/options/$id/edit'
    | '/admin/templates/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/options': {
      id: '/admin/options'
      path: '/options'
      fullPath: '/admin/options'
      preLoaderRoute: typeof AdminOptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/templates/': {
      id: '/admin/templates/'
      path: '/'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin/options/': {
      id: '/admin/options/'
      path: '/'
      fullPath: '/admin/options/'
      preLoaderRoute: typeof AdminOptionsIndexRouteImport
      parentRoute: typeof AdminOptionsRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/api-keys/': {
      id: '/admin/api-keys/'
      path: '/'
      fullPath: '/admin/api-keys/'
      preLoaderRoute: typeof AdminApiKeysIndexRouteImport
      parentRoute: typeof AdminApiKeysRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator/': {
      id: '/_app/generator/'
      path: '/generator'
      fullPath: '/generator/'
      preLoaderRoute: typeof AppGeneratorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/templates/create': {
      id: '/admin/templates/create'
      path: '/create'
      fullPath: '/admin/templates/create'
      preLoaderRoute: typeof AdminTemplatesCreateRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin/options/create': {
      id: '/admin/options/create'
      path: '/create'
      fullPath: '/admin/options/create'
      preLoaderRoute: typeof AdminOptionsCreateRouteImport
      parentRoute: typeof AdminOptionsRoute
    }
    '/admin/categories/create': {
      id: '/admin/categories/create'
      path: '/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminCategoriesCreateRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/api-keys/create': {
      id: '/admin/api-keys/create'
      path: '/create'
      fullPath: '/admin/api-keys/create'
      preLoaderRoute: typeof AdminApiKeysCreateRouteImport
      parentRoute: typeof AdminApiKeysRoute
    }
    '/_app/templates/$slug': {
      id: '/_app/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof AppTemplatesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator/result': {
      id: '/_app/generator/result'
      path: '/generator/result'
      fullPath: '/generator/result'
      preLoaderRoute: typeof AppGeneratorResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/templates/$id/edit': {
      id: '/admin/templates/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/templates/$id/edit'
      preLoaderRoute: typeof AdminTemplatesIdEditRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin/options/$id/edit': {
      id: '/admin/options/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/options/$id/edit'
      preLoaderRoute: typeof AdminOptionsIdEditRouteImport
      parentRoute: typeof AdminOptionsRoute
    }
    '/admin/categories/$id/edit': {
      id: '/admin/categories/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof AdminCategoriesIdEditRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppGeneratorResultRoute: typeof AppGeneratorResultRoute
  AppTemplatesSlugRoute: typeof AppTemplatesSlugRoute
  AppGeneratorIndexRoute: typeof AppGeneratorIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppGeneratorResultRoute: AppGeneratorResultRoute,
  AppTemplatesSlugRoute: AppTemplatesSlugRoute,
  AppGeneratorIndexRoute: AppGeneratorIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminApiKeysRouteChildren {
  AdminApiKeysCreateRoute: typeof AdminApiKeysCreateRoute
  AdminApiKeysIndexRoute: typeof AdminApiKeysIndexRoute
}

const AdminApiKeysRouteChildren: AdminApiKeysRouteChildren = {
  AdminApiKeysCreateRoute: AdminApiKeysCreateRoute,
  AdminApiKeysIndexRoute: AdminApiKeysIndexRoute,
}

const AdminApiKeysRouteWithChildren = AdminApiKeysRoute._addFileChildren(
  AdminApiKeysRouteChildren,
)

interface AdminCategoriesRouteChildren {
  AdminCategoriesCreateRoute: typeof AdminCategoriesCreateRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCategoriesIdEditRoute: typeof AdminCategoriesIdEditRoute
}

const AdminCategoriesRouteChildren: AdminCategoriesRouteChildren = {
  AdminCategoriesCreateRoute: AdminCategoriesCreateRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCategoriesIdEditRoute: AdminCategoriesIdEditRoute,
}

const AdminCategoriesRouteWithChildren = AdminCategoriesRoute._addFileChildren(
  AdminCategoriesRouteChildren,
)

interface AdminOptionsRouteChildren {
  AdminOptionsCreateRoute: typeof AdminOptionsCreateRoute
  AdminOptionsIndexRoute: typeof AdminOptionsIndexRoute
  AdminOptionsIdEditRoute: typeof AdminOptionsIdEditRoute
}

const AdminOptionsRouteChildren: AdminOptionsRouteChildren = {
  AdminOptionsCreateRoute: AdminOptionsCreateRoute,
  AdminOptionsIndexRoute: AdminOptionsIndexRoute,
  AdminOptionsIdEditRoute: AdminOptionsIdEditRoute,
}

const AdminOptionsRouteWithChildren = AdminOptionsRoute._addFileChildren(
  AdminOptionsRouteChildren,
)

interface AdminTemplatesRouteChildren {
  AdminTemplatesCreateRoute: typeof AdminTemplatesCreateRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
  AdminTemplatesIdEditRoute: typeof AdminTemplatesIdEditRoute
}

const AdminTemplatesRouteChildren: AdminTemplatesRouteChildren = {
  AdminTemplatesCreateRoute: AdminTemplatesCreateRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
  AdminTemplatesIdEditRoute: AdminTemplatesIdEditRoute,
}

const AdminTemplatesRouteWithChildren = AdminTemplatesRoute._addFileChildren(
  AdminTemplatesRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOptionsRoute: typeof AdminOptionsRouteWithChildren
  AdminTemplatesRoute: typeof AdminTemplatesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOptionsRoute: AdminOptionsRouteWithChildren,
  AdminTemplatesRoute: AdminTemplatesRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
